

version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"

# to build and run the docker container, use the following command in the terminal
      # docker-compose up --build


# stop the container, use the following command in the terminal
      # docker-compose down

      
# Frontend → localhost:3000
# FastAPI → localhost:8000